name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/<your-username>/<image-name>:latest .
          docker push ghcr.io/<your-username>/<image-name>:latest

      - name: Run Docker container
        run: |
          docker run -d --name mcp-seq-container -e SEQ_API_KEY=${{ secrets.SEQ_API_KEY }} -p 8080:8080 ghcr.io/<your-username>/<image-name>:latest

      - name: Check Docker container status
        run: |
          sleep 10
          docker ps -a
          docker logs mcp-seq-container
          docker inspect --format='{{.State.Health.Status}}' mcp-seq-container
